name: CI

on:
  push:
    branches: "main"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-11
          - macos-12
    steps:
      - uses: actions/checkout@v3
      - run: make
      - run: julia -E '@ccall "./libbar.dylib".bar()::Cint'
