name: CI

on:
  push:
    branches: "main"

jobs:
  test:
    name: Test - macOS ${{ matrix.os }} - MACOSX_VERSION_MIN ${{ matrix.macosx-version-min }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-11
          - macos-12
        macosx-version-min:
          - "10.10"
          - "10.13"
          - "10.14"
    steps:
      - uses: actions/checkout@v3
      - run: make MACOSX_VERSION_MIN=${{ matrix.macosx-version-min }}
