name: CI

on:
  push:
    branches: "main"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: make
